#!/bin/sh
set -e

case $1 in
remove)
	firmware="/lib/firmware"

	files="
	$firmware/rockchip/dptx.bin \
	$firmware/rtl_bt/rtl8822cs_config.bin \
	$firmware/rtl_bt/rtl8822cs_fw.bin \
	$firmware/rtlbt/rtl8822cs_config \
	$firmware/rtlbt/rtl8822cs_fw \
	$firmware/rtw88/rtw8822c_fw.bin \
	$firmware/rtw88/rtw8822c_wow_fw.bin \
	$firmware/rtlbt/rtl8852bs_config \
	$firmware/rtlbt/rtl8852bs_fw \
	"

	for i in $files; do
		dpkg-divert --package vicharak-firmware --rename --remove "$i"
	done
	;;
esac

exit 0
