#!/bin/sh
set -e

#DEBHELPER#

case $1 in
install | upgrade)
	firmware="/lib/firmware"

	files="
	$firmware/rockchip/dptx.bin \
	$firmware/rtl_bt/rtl8822cs_config.bin \
	$firmware/rtl_bt/rtl8822cs_fw.bin \
	$firmware/rtlbt/rtl8822cs_config \
	$firmware/rtlbt/rtl8822cs_fw \
	$firmware/rtw88/rtw8822c_fw.bin \
	$firmware/rtw88/rtw8822c_wow_fw.bin \
	"

	for i in $files; do
		dpkg-divert --package vicharak-firmware --divert "$i.bak" --rename "$i"
	done
	;;
esac

#DEBHELPER#

exit 0
